In [ ]:
#Reference and read : https://github.com/opencv/opencv/tree/master/data/haarcascades
#                     https://towardsdatascience.com/face-recognition-how-lbph-works-90ec258c3d6b

In [1]:
import numpy
import os
import cv2

In [ ]:
#!pip install opencv-python

In [ ]:
#!python -m pip install --user opencv-contrib-python

In [2]:
def faceDetection(test_img):             
    gray_img=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)   #convert image from color to grey format to make less computation
    face_haar=cv2.CascadeClassifier('haarcascade_frontalface_alt.xml') #Give path to haar classifier as i have given
    faces=face_haar.detectMultiScale(gray_img,scaleFactor=1.2,minNeighbors=3)
    return faces,gray_img

In [4]:
#cv2.__version__

In [10]:
img = cv2.imread(r'C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0001.jpg')
faceDetection(img)

(array([[298, 178, 204, 204]], dtype=int32),
 array([[182, 180, 179, ..., 197, 195, 193],
        [180, 178, 177, ..., 197, 196, 194],
        [180, 178, 178, ..., 195, 194, 193],
        ...,
        [112, 111, 111, ..., 124, 126, 126],
        [116, 114, 112, ..., 123, 125, 125],
        [117, 115, 112, ..., 122, 123, 123]], dtype=uint8))

In [9]:
#create dataset and store it 
'''
import cv2
import sys

cpt = 0
vidStream = cv2.VideoCapture(0)

while(True):
    ret,frame = vidStream.read()
    cv2.imshow('Capturing Video',frame)
    cv2.imwrite(r"C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image%04i.jpg" %cpt, frame)
    cpt +=1
    if cv2.waitKey(10)==ord('q'):
        vidStream.release()
        cv2.destroyAllWindows()
        break
'''

In [3]:
def labels_for_training_data(directory):
    faces=[]
    faceID=[]
    
    for path, subdirnames, filenames in os.walk(directory):
        for filename in filenames:
            if filename.startswith("."): #if anything starting with . is considerd as non image
                print("skipping system file")
                continue
            id = os.path.basename(path)
            img_path = os.path.join(path, filename)
            print("img_path", img_path)
            print("id", id)
            test_img = cv2.imread(img_path)
            if test_img is None:
                print("Not loaded properly")
                continue
            faces_rect, gray_img = faceDetection(test_img)
            (x,y,w,h) = faces_rect[0]
            roi_gray = gray_img[y:y+w, x:x+h]
            faces.append(roi_gray)
            faceID.append(int(id))
            
    return faces, faceID
                

In [4]:
#Here training Classifier is called
def train_classifier(faces,faceID):                              
    face_recognizer=cv2.face.LBPHFaceRecognizer_create()
    face_recognizer.train(faces,np.array(faceID))
    return face_recognizer


#Drawing a Rectangle on the Face Function
def draw_rect(test_img,face):                                      
    (x,y,w,h)=face
    cv2.rectangle(test_img,(x,y),(x+w,y+h),(0,255,0),thickness=3)   #b,g,r = 0,255,0

#Putting text on images
def put_text(test_img,text,x,y):                                    
    cv2.putText(test_img,text,(x,y),cv2.FONT_HERSHEY_DUPLEX,3,(255,0,0),6)
    
    

In [13]:
#training the model

import numpy as np
import cv2
import os


test_img=cv2.imread(r"C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0001.jpg")  #Give path to the image which you want to test


faces_detected,gray_img=faceDetection(test_img)
print("face Detected: ",faces_detected)

#Training will begin from here

faces,faceID=labels_for_training_data(r'C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset') #Give path to the train-images folder which has both labeled folder as 0 and 1
face_recognizer=train_classifier(faces,faceID)
face_recognizer.save(r"C:\Users\Admin\OTHER PROJECTS\facial recognition\trainingData.yml") #It will save the trained model. Just give path to where you want to save

name={0:"Sarang"}    #Change names accordingly. If you want to recognize only one person then write:- name={0:"name"} thats all. Dont write for id number 1.


for face in faces_detected:
    (x,y,w,h)=face
    roi_gray=gray_img[y:y+h,x:x+h]
    label,confidence=face_recognizer.predict(roi_gray)
    print ("Confidence :",confidence)
    print("label :",label)
    draw_rect(test_img,face)
    predicted_name=name[label]
    put_text(test_img,predicted_name,x,y)

resized_img=cv2.resize(test_img,(1000,700))

cv2.imshow("face detection ", resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows




face Detected:  [[298 178 204 204]]
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0000.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0001.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0002.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0003.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0004.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0005.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0006.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0007.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0008.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0009.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognit

img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0090.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0091.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0092.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0093.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0094.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0095.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0096.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0097.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0098.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0099.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0100.jpg
id 0

img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0181.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0182.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0183.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0184.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0185.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0186.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0187.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0188.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0189.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0190.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0191.jpg
id 0

img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0272.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0273.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0274.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0275.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0276.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0277.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0278.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0279.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0280.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0281.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0282.jpg
id 0

img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0364.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0365.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0366.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0367.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0368.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0369.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0370.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0371.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0372.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0373.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0374.jpg
id 0

img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0455.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0456.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0457.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0458.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0459.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0460.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0461.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0462.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0463.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0464.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0465.jpg
id 0

img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0546.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0547.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0548.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0549.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0550.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0551.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0552.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0553.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0554.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0555.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0556.jpg
id 0

img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0637.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0638.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0639.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0640.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0641.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0642.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0643.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0644.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0645.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0646.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0647.jpg
id 0

img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0818.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0819.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0820.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0821.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0822.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0823.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0824.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0825.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0826.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0827.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0828.jpg
id 0

img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0910.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0911.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0912.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0913.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0914.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0915.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0916.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0917.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0918.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0919.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image0920.jpg
id 0

img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1001.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1002.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1003.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1004.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1005.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1006.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1007.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1008.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1009.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1010.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1011.jpg
id 0

img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1183.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1184.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1185.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1186.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1187.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1188.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1189.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1190.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1191.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1192.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1193.jpg
id 0

img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1274.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1275.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1276.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1277.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1278.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1279.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1280.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1281.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1282.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1283.jpg
id 0
img_path C:\Users\Admin\OTHER PROJECTS\facial recognition\facedataset\0\image1284.jpg
id 0

<function destroyAllWindows>

In [8]:
#testing and capturing image from camera
import numpy as np
import cv2
import os


face_recognizer=cv2.face.LBPHFaceRecognizer_create()
face_recognizer.read(r"C:\Users\Admin\OTHER PROJECTS\facial recognition\trainingData.yml")    #Give path of where trainingData.yml is saved

vidStream=cv2.VideoCapture(0)   #If you want to recognise face from a video then replace 0 with video path

name={0:"Sarang"}    #Change names accordingly. 
while True:
    ret,test_img=vidStream.read()
    faces_detected,gray_img=faceDetection(test_img)
    print("face Detected: ",faces_detected)
    for (x,y,w,h) in faces_detected:
        cv2.rectangle(test_img,(x,y),(x+w,y+h),(0,255,0),thickness=5)
    
    for face in faces_detected:
        (x,y,w,h)=face
        roi_gray=gray_img[y:y+h,x:x+h]
        label,confidence=face_recognizer.predict(roi_gray)
        print ("Confidence :",confidence)
        print("label :",label)
        draw_rect(test_img,face)
        predicted_name=name[label]
        put_text(test_img,predicted_name,x,y)

    resized_img=cv2.resize(test_img,(1000,700))

    cv2.imshow("face detection ", resized_img)
    if cv2.waitKey(10)==ord('q'):
        vidStream.release()
        cv2.destroyAllWindows
        break


face Detected:  [[290 221 147 147]]
Confidence : 32.401543622258835
label : 0
face Detected:  [[290 218 147 147]]
Confidence : 30.945834964563964
label : 0
face Detected:  [[286 214 157 157]]
Confidence : 32.06450475635819
label : 0
face Detected:  [[515 217  58  58]
 [290 218 148 148]]
Confidence : 90.4867882456966
label : 0
Confidence : 32.5837339765921
label : 0
face Detected:  [[287 219 150 150]]
Confidence : 31.598038291124936
label : 0
face Detected:  [[288 219 149 149]]
Confidence : 33.053329849711005
label : 0
face Detected:  [[294 217 151 151]]
Confidence : 30.907957588278297
label : 0
face Detected:  [[289 217 149 149]]
Confidence : 33.72030314536051
label : 0
face Detected:  [[285 217 152 152]]
Confidence : 31.95295941522036
label : 0
face Detected:  [[286 218 147 147]]
Confidence : 33.82680194918249
label : 0
face Detected:  [[516 218  58  58]
 [284 217 150 150]]
Confidence : 96.50718764949521
label : 0
Confidence : 31.64628511761949
label : 0
face Detected:  [[286 218 148 